### ISSUE TITLE
运行报错：Load model from ./hivision_modnet.onnx failed:Protobuf parsing failed

### ISSUE THREAD

**Issue by jhonboHou** [xiaolin199912/HivisionIDPhotos#9]
![image](https://github.com/xiaolin199912/HivisionIDPhotos/assets/49391942/53d0bd17-2993-4891-bd0d-3d7ba5210ad7)

**Comment by jhonboHou** [comment]
找到原因了

**Comment by luckykong** [comment]
是什么原因？能说一下么？

**Comment by fmw666** [comment]
> 是什么原因？能说一下么？

检查一下你的 hivision_modnet.onnx 文件是否损坏，正常文件大小 24.6MB（md5值 ae9b6ec96dadb1905d9ba36fdd0077b2）
